### PR TITLE
Make C++ standard configurable, with default to C++14

### PR DESCRIPTION
**Pull request by bennybp**
I don't know if we have specific CMake version in mind. According to somewhere on the CMake website, CMake 3.1.3 was released Feb 2015

### CODE REVIEW

**Comment by ryanmrichard** [comment]
I'm going to ignore that broken push...

**Comment by bennybp** [comment]
Yeah that looks like a problem with tavis and gcc4.9??

**Comment by loriab** [comment]
Don't know if it matters, but psi4 is defaulting to C++11. We can try 14 once all other pb11 issues stable.

**Comment by bennybp** [comment]
I'm don't think there should be any problems if psi4 is compiled with C++11, although it might be nice to make it configurable like I did here (compiling C++11 code as C++14 should work. I don't think there are any major deprecations). But I don't think it's necessary at the moment.

**Comment by loriab** [comment]
it's configurable through `-Dpsi_CXX_STANDARD=14`. But I have no idea if that compiles.

**Pull request merged**
